/**
 * Retired corridor pages — HTTP 410 Gone.
 *
 * Context (2026-06-25 cleanup): On 2026-03-20 a one-day 95% Google-impression
 * cliff followed the Mar 16-17 launch of 200+ programmatic pages on a months-old
 * domain — the signature of an algorithmic scaled-content reassessment (no manual
 * action; confirmed clean in Search Console). Recovery requires shrinking the
 * thin/templated footprint so the indexed-page quality average rises before the
 * next core update re-evaluates the site.
 *
 * These 53 slugs are hand-written editorial corridors that earned ZERO sessions
 * and ZERO key events across ALL channels (Google + Bing + AI assistants) over
 * the 90-day window, are NOT in the sitemap allowlist, and are NOT high-demand
 * head-terms (those — usa-to-india, uk-to-pakistan, uae-to-philippines, etc. —
 * are deliberately KEPT and re-submitted, because their zero traffic reflects
 * Google suppression, not low demand).
 *
 * 410 (not 404, not 301): 410 tells Google the URL is intentionally retired, so
 * it deindexes cleanly. 404 reads as "never existed" and lingers; 301 reads as
 * "content moved" which contradicts scaled-content remediation. These pages have
 * no sensible live equivalent to redirect to, so 410 is correct.
 *
 * Promote OUT of this set only if a slug starts earning real demand on Bing/AI.
 */
export const GONE_CORRIDOR_SLUGS = new Set<string>([
  "europe-to-india",
  "europe-to-nigeria",
  "europe-to-pakistan",
  "europe-to-philippines",
  "europe-to-ukraine",
  "hong-kong-to-india",
  "hong-kong-to-philippines",
  "india-to-australia",
  "ireland-to-malaysia",
  "ireland-to-philippines",
  "japan-to-india",
  "japan-to-philippines",
  "japan-to-usa",
  "malaysia-to-india",
  "malaysia-to-indonesia",
  "malaysia-to-philippines",
  "new-zealand-to-fiji",
  "new-zealand-to-india",
  "new-zealand-to-philippines",
  "singapore-to-bangladesh",
  "singapore-to-indonesia",
  "south-africa-to-kenya",
  "south-africa-to-nigeria",
  "south-africa-to-uk",
  "south-korea-to-philippines",
  "south-korea-to-vietnam",
  "sweden-to-brazil",
  "sweden-to-colombia",
  "sweden-to-mexico",
  "sweden-to-morocco",
  "sweden-to-philippines",
  "sweden-to-romania",
  "switzerland-to-india",
  "switzerland-to-philippines",
  "uae-to-egypt",
  "uae-to-nepal",
  "uk-to-europe",
  "uk-to-ghana",
  "uk-to-jamaica",
  "uk-to-nepal",
  "uk-to-south-africa",
  "uk-to-sri-lanka",
  "uk-to-ukraine",
  "usa-to-brazil",
  "usa-to-colombia",
  "usa-to-dominican-republic",
  "usa-to-guatemala",
  "usa-to-haiti",
  "usa-to-honduras",
  "usa-to-indonesia",
  "usa-to-jamaica",
  "usa-to-nepal",
  "usa-to-ukraine",
  // ── 2026-08-31: Eurozone duplicate collapse (327 slugs) ─────────────────
  //
  // Every Eurozone country x destination had its own URL, but they all resolve
  // to the same currency pair, so the pages were near-identical. Measured
  // 8-gram Jaccard on full rendered text: 88.7-90.9% between siblings
  // (france/germany/spain/italy-to-thailand). Unrelated corridors score 8-14%,
  // so the template is fine - the duplication was specific to EUR-source
  // siblings, where only the country name differed. Of 4,195 8-grams on
  // france-to-thailand, just 249 (5.9%) were absent from germany-to-thailand.
  //
  // The Aug 27 sitemap carried 1,013 URLs (752 corridors) - up from the ~178
  // that the May right-sizing left. That regrowth re-created the scaled-content
  // surface behind the 2026-03-20 impression cliff, at larger scale than before.
  //
  // ONE canonical page survives per EUR->destination pair (35 clusters). The
  // survivor is chosen by real demand where any exists (Bing per-page
  // impressions + GSC 90d), otherwise by outbound-remittance market rank
  // (germany > france > spain > italy > ...). Four slugs that would have been
  // cut were spared because they carry demand or sit on a protection list:
  // ireland-to-bangladesh, italy-to-brazil, france-to-pakistan (head/allowlist)
  // and france-to-turkey (2 Bing impressions).
  //
  // 410 not 301, consistent with the rest of this file: 301 reads as "content
  // moved", which contradicts scaled-content remediation. The surviving sibling
  // is not a redirect target for the others - it is the same comparison, and
  // Google should see the duplicates as retired rather than relocated.
  //
  // Promote OUT of this set only if a slug starts earning real demand on
  // Bing/AI - same readmit policy as the 2026-06-25 block above.
  "austria-to-argentina",
  "austria-to-bangladesh",
  "austria-to-brazil",
  "austria-to-chile",
  "austria-to-colombia",
  "austria-to-dominican-republic",
  "austria-to-ecuador",
  "austria-to-egypt",
  "austria-to-el-salvador",
  "austria-to-ghana",
  "austria-to-honduras",
  "austria-to-hong-kong",
  "austria-to-india",
  "austria-to-indonesia",
  "austria-to-japan",
  "austria-to-kenya",
  "austria-to-malaysia",
  "austria-to-mexico",
  "austria-to-morocco",
  "austria-to-nigeria",
  "austria-to-pakistan",
  "austria-to-panama",
  "austria-to-peru",
  "austria-to-philippines",
  "austria-to-poland",
  "austria-to-singapore",
  "austria-to-south-africa",
  "austria-to-south-korea",
  "austria-to-thailand",
  "austria-to-uk",
  "austria-to-ukraine",
  "austria-to-vietnam",
  "austria-to-zimbabwe",
  "belgium-to-argentina",
  "belgium-to-bangladesh",
  "belgium-to-brazil",
  "belgium-to-chile",
  "belgium-to-colombia",
  "belgium-to-dominican-republic",
  "belgium-to-ecuador",
  "belgium-to-egypt",
  "belgium-to-el-salvador",
  "belgium-to-ghana",
  "belgium-to-honduras",
  "belgium-to-hong-kong",
  "belgium-to-india",
  "belgium-to-indonesia",
  "belgium-to-japan",
  "belgium-to-kenya",
  "belgium-to-malaysia",
  "belgium-to-mexico",
  "belgium-to-nigeria",
  "belgium-to-panama",
  "belgium-to-peru",
  "belgium-to-philippines",
  "belgium-to-poland",
  "belgium-to-singapore",
  "belgium-to-south-africa",
  "belgium-to-south-korea",
  "belgium-to-thailand",
  "belgium-to-turkey",
  "belgium-to-uk",
  "belgium-to-ukraine",
  "belgium-to-vietnam",
  "belgium-to-zimbabwe",
  "finland-to-argentina",
  "finland-to-bangladesh",
  "finland-to-brazil",
  "finland-to-chile",
  "finland-to-colombia",
  "finland-to-dominican-republic",
  "finland-to-ecuador",
  "finland-to-egypt",
  "finland-to-el-salvador",
  "finland-to-ghana",
  "finland-to-honduras",
  "finland-to-hong-kong",
  "finland-to-india",
  "finland-to-indonesia",
  "finland-to-japan",
  "finland-to-kenya",
  "finland-to-malaysia",
  "finland-to-mexico",
  "finland-to-morocco",
  "finland-to-nigeria",
  "finland-to-pakistan",
  "finland-to-panama",
  "finland-to-peru",
  "finland-to-poland",
  "finland-to-singapore",
  "finland-to-south-africa",
  "finland-to-south-korea",
  "finland-to-thailand",
  "finland-to-turkey",
  "finland-to-uk",
  "finland-to-ukraine",
  "finland-to-vietnam",
  "finland-to-zimbabwe",
  "france-to-argentina",
  "france-to-bangladesh",
  "france-to-brazil",
  "france-to-chile",
  "france-to-colombia",
  "france-to-dominican-republic",
  "france-to-ecuador",
  "france-to-egypt",
  "france-to-el-salvador",
  "france-to-honduras",
  "france-to-hong-kong",
  "france-to-india",
  "france-to-indonesia",
  "france-to-japan",
  "france-to-kenya",
  "france-to-malaysia",
  "france-to-mexico",
  "france-to-morocco",
  "france-to-nigeria",
  "france-to-panama",
  "france-to-peru",
  "france-to-philippines",
  "france-to-poland",
  "france-to-singapore",
  "france-to-south-africa",
  "france-to-south-korea",
  "france-to-thailand",
  "france-to-ukraine",
  "france-to-vietnam",
  "france-to-zimbabwe",
  "germany-to-bangladesh",
  "germany-to-brazil",
  "germany-to-uk",
  "greece-to-argentina",
  "greece-to-bangladesh",
  "greece-to-brazil",
  "greece-to-chile",
  "greece-to-colombia",
  "greece-to-dominican-republic",
  "greece-to-ecuador",
  "greece-to-egypt",
  "greece-to-el-salvador",
  "greece-to-ghana",
  "greece-to-honduras",
  "greece-to-hong-kong",
  "greece-to-india",
  "greece-to-indonesia",
  "greece-to-japan",
  "greece-to-kenya",
  "greece-to-malaysia",
  "greece-to-mexico",
  "greece-to-morocco",
  "greece-to-nigeria",
  "greece-to-pakistan",
  "greece-to-panama",
  "greece-to-peru",
  "greece-to-philippines",
  "greece-to-singapore",
  "greece-to-south-africa",
  "greece-to-south-korea",
  "greece-to-thailand",
  "greece-to-turkey",
  "greece-to-uk",
  "greece-to-ukraine",
  "greece-to-vietnam",
  "greece-to-zimbabwe",
  "ireland-to-argentina",
  "ireland-to-chile",
  "ireland-to-colombia",
  "ireland-to-dominican-republic",
  "ireland-to-ecuador",
  "ireland-to-egypt",
  "ireland-to-el-salvador",
  "ireland-to-ghana",
  "ireland-to-honduras",
  "ireland-to-hong-kong",
  "ireland-to-india",
  "ireland-to-indonesia",
  "ireland-to-japan",
  "ireland-to-kenya",
  "ireland-to-mexico",
  "ireland-to-morocco",
  "ireland-to-nigeria",
  "ireland-to-pakistan",
  "ireland-to-panama",
  "ireland-to-peru",
  "ireland-to-poland",
  "ireland-to-singapore",
  "ireland-to-south-africa",
  "ireland-to-south-korea",
  "ireland-to-thailand",
  "ireland-to-turkey",
  "ireland-to-uk",
  "ireland-to-ukraine",
  "ireland-to-vietnam",
  "ireland-to-zimbabwe",
  "italy-to-argentina",
  "italy-to-bangladesh",
  "italy-to-chile",
  "italy-to-colombia",
  "italy-to-dominican-republic",
  "italy-to-ecuador",
  "italy-to-egypt",
  "italy-to-el-salvador",
  "italy-to-ghana",
  "italy-to-honduras",
  "italy-to-hong-kong",
  "italy-to-india",
  "italy-to-indonesia",
  "italy-to-japan",
  "italy-to-kenya",
  "italy-to-malaysia",
  "italy-to-mexico",
  "italy-to-morocco",
  "italy-to-nigeria",
  "italy-to-pakistan",
  "italy-to-panama",
  "italy-to-peru",
  "italy-to-philippines",
  "italy-to-poland",
  "italy-to-singapore",
  "italy-to-south-africa",
  "italy-to-south-korea",
  "italy-to-thailand",
  "italy-to-turkey",
  "italy-to-uk",
  "italy-to-ukraine",
  "italy-to-vietnam",
  "italy-to-zimbabwe",
  "netherlands-to-argentina",
  "netherlands-to-bangladesh",
  "netherlands-to-brazil",
  "netherlands-to-chile",
  "netherlands-to-colombia",
  "netherlands-to-dominican-republic",
  "netherlands-to-ecuador",
  "netherlands-to-egypt",
  "netherlands-to-el-salvador",
  "netherlands-to-ghana",
  "netherlands-to-honduras",
  "netherlands-to-hong-kong",
  "netherlands-to-india",
  "netherlands-to-indonesia",
  "netherlands-to-japan",
  "netherlands-to-kenya",
  "netherlands-to-malaysia",
  "netherlands-to-mexico",
  "netherlands-to-morocco",
  "netherlands-to-nigeria",
  "netherlands-to-pakistan",
  "netherlands-to-panama",
  "netherlands-to-peru",
  "netherlands-to-poland",
  "netherlands-to-singapore",
  "netherlands-to-south-africa",
  "netherlands-to-south-korea",
  "netherlands-to-thailand",
  "netherlands-to-turkey",
  "netherlands-to-uk",
  "netherlands-to-ukraine",
  "netherlands-to-vietnam",
  "netherlands-to-zimbabwe",
  "portugal-to-argentina",
  "portugal-to-brazil",
  "portugal-to-chile",
  "portugal-to-colombia",
  "portugal-to-dominican-republic",
  "portugal-to-ecuador",
  "portugal-to-egypt",
  "portugal-to-el-salvador",
  "portugal-to-ghana",
  "portugal-to-honduras",
  "portugal-to-hong-kong",
  "portugal-to-india",
  "portugal-to-indonesia",
  "portugal-to-japan",
  "portugal-to-kenya",
  "portugal-to-malaysia",
  "portugal-to-mexico",
  "portugal-to-morocco",
  "portugal-to-nigeria",
  "portugal-to-pakistan",
  "portugal-to-panama",
  "portugal-to-peru",
  "portugal-to-philippines",
  "portugal-to-poland",
  "portugal-to-singapore",
  "portugal-to-south-africa",
  "portugal-to-south-korea",
  "portugal-to-thailand",
  "portugal-to-turkey",
  "portugal-to-uk",
  "portugal-to-ukraine",
  "portugal-to-vietnam",
  "portugal-to-zimbabwe",
  "spain-to-argentina",
  "spain-to-bangladesh",
  "spain-to-brazil",
  "spain-to-chile",
  "spain-to-colombia",
  "spain-to-dominican-republic",
  "spain-to-ecuador",
  "spain-to-egypt",
  "spain-to-el-salvador",
  "spain-to-ghana",
  "spain-to-honduras",
  "spain-to-hong-kong",
  "spain-to-india",
  "spain-to-indonesia",
  "spain-to-japan",
  "spain-to-kenya",
  "spain-to-malaysia",
  "spain-to-mexico",
  "spain-to-morocco",
  "spain-to-nigeria",
  "spain-to-pakistan",
  "spain-to-panama",
  "spain-to-peru",
  "spain-to-philippines",
  "spain-to-poland",
  "spain-to-singapore",
  "spain-to-south-africa",
  "spain-to-south-korea",
  "spain-to-thailand",
  "spain-to-turkey",
  "spain-to-uk",
  "spain-to-ukraine",
  "spain-to-vietnam",
  "spain-to-zimbabwe",
]);
