/**
 * GSC-validated slugs that earned ≥10 impressions in the 90-day window
 * Feb 18 – May 19, 2026. These are the URLs the sitemap submits.
 *
 * Re-run scripts/regenerate-sitemap-allowlist.ts when the next GSC pull
 * is fresh enough to recalibrate.
 */

export const SITEMAP_CORRIDOR_SLUGS = new Set<string>([
  "aud-to-bdt",
  "aud-to-cad",
  "aud-to-cny",
  "aud-to-cop",
  "aud-to-eur",
  "aud-to-fjd",
  "aud-to-gbp",
  "aud-to-idr",
  "aud-to-lkr",
  "aud-to-usd",
  "aud-to-vnd",
  "australia-to-bangladesh",
  "australia-to-brazil",
  "australia-to-china",
  "australia-to-guatemala",
  "australia-to-indonesia",
  "australia-to-japan",
  "australia-to-kenya",
  "australia-to-mexico",
  "australia-to-morocco",
  "australia-to-nepal",
  "australia-to-pakistan",
  "australia-to-philippines",
  "australia-to-south-africa",
  "australia-to-sri-lanka",
  "australia-to-tanzania",
  "australia-to-thailand",
  "australia-to-turkey",
  "australia-to-uae",
  "australia-to-uganda",
  "austria-to-turkey",
  "belgium-to-australia",
  "belgium-to-morocco",
  "belgium-to-pakistan",
  "cad-to-bdt",
  "cad-to-eur",
  "cad-to-gbp",
  "cad-to-ghs",
  "cad-to-hkd",
  "cad-to-mxn",
  "canada-to-australia",
  "canada-to-bangladesh",
  "canada-to-cameroon",
  "canada-to-china",
  "canada-to-egypt",
  "canada-to-fiji",
  "canada-to-ghana",
  "canada-to-indonesia",
  "canada-to-jamaica",
  "canada-to-malaysia",
  "canada-to-mexico",
  "canada-to-nepal",
  "canada-to-nigeria",
  "canada-to-pakistan",
  "canada-to-philippines",
  "canada-to-poland",
  "canada-to-romania",
  "canada-to-vietnam",
  "denmark-to-bangladesh",
  "denmark-to-brazil",
  "denmark-to-china",
  "denmark-to-colombia",
  "germany-to-ghana",
  "uk-to-bangladesh",
  // Note: GSC also showed impressions on legacy /send-money/send-money-to-morocco
  // and /send-money/send-money-to-spain (auto-generated dupes of /send-money/morocco
  // and /send-money/spain). Those aren't in src/data/corridors.ts and shouldn't
  // be submitted — they're a separate duplicate-content issue to fix later.
]); // 64 URLs

export const SITEMAP_GUIDE_SLUGS = new Set<string>([
  "best-money-transfer-apps",
  "best-money-transfer-rates-eid-holi-2026",
  "best-money-transfer-services",
  "business-international-payments-guide",
  "business-payments-uk-to-europe",
  "cost-of-sending-1000-abroad",
  "crypto-banking-licenses-2026",
  "global-remittance-trends-2026",
  "how-euribor-affects-euro-transfers",
  "how-to-pay-international-suppliers",
  "iban-numbers-explained",
  "money-transfer-promo-codes-referral-programs",
  "money-transfer-safety-guide",
  "multi-currency-accounts-exchange-rates",
  "pakistan-rupee-forecast-2026",
  "send-money-to-bangladesh-guide",
  "send-money-to-india-cash-pickup-ria",
  "send-money-to-india-guide",
  "send-money-to-mexico-guide",
  "send-money-to-nigeria-guide",
  "send-money-to-pakistan-guide",
  "send-money-to-philippines-guide",
  "send-money-to-south-africa-guide",
  "send-money-uk-to-india-guide",
  "swift-codes-explained",
  "us-dollar-forecast-2026",
  "wire-transfer-guide",
]); // 27 URLs

export const SITEMAP_IBAN_SLUGS = new Set<string>([
  "andorra",
  "austria",
  "belgium",
  "brazil",
  "costa-rica",
  "croatia",
  "cyprus",
  "czechia",
  "denmark",
  "egypt",
  "el-salvador",
  "finland",
  "france",
  "georgia",
  "germany",
  "greece",
  "hungary",
  "ireland",
  "israel",
  "jordan",
  "lithuania",
  "luxembourg",
  "monaco",
  "netherlands",
  "norway",
  "pakistan",
  "poland",
  "portugal",
  "romania",
  "slovakia",
  "spain",
  "sweden",
  "switzerland",
  "turkey",
  "uk",
  "ukraine",
  "united-arab-emirates",
]); // 37 URLs

export const SITEMAP_COMPARISON_SLUGS = new Set<string>([
  "lloyds-vs-nationwide",
  "moneygram-vs-taptap-send",
  "moneygram-vs-xoom",
  "ofx-vs-moneygram",
  "ofx-vs-xe",
  "ofx-vs-xoom",
  "paypal-vs-moneygram",
  "paypal-vs-xoom",
  "remitly-vs-moneygram",
  "remitly-vs-paypal",
  "remitly-vs-revolut",
  "remitly-vs-taptap-send",
  "remitly-vs-worldremit",
  "remitly-vs-xe",
  "remitly-vs-xoom",
  "revolut-vs-chase",
  "revolut-vs-lloyds",
  "revolut-vs-taptap-send",
  "revolut-vs-wells-fargo",
  "western-union-vs-bank-of-america",
  "western-union-vs-moneygram",
  "western-union-vs-paypal",
  "western-union-vs-worldremit",
  "wise-vs-ofx",
  "wise-vs-paypal",
  "wise-vs-revolut",
  "wise-vs-taptap-send",
  "wise-vs-worldremit",
  "wise-vs-xoom",
  "worldremit-vs-revolut",
  "worldremit-vs-taptap-send",
  "xoom-vs-taptap-send",
]); // 32 URLs

export const SITEMAP_PROVIDER_SLUGS = new Set<string>([
  "ace-money-transfer",
  "moneygram",
  "paypal",
  "revolut",
  "xe",
  "xoom",
]); // 6 URLs

export const SITEMAP_NEWS_SLUGS = new Set<string>([
  "central-bank-super-week-march-2026",
  "china-digital-yuan-interest-bearing-cbdc",
  "embedded-finance-regulation-tightening-2026",
  "eu-instant-payments-mandate-2026",
  "revolut-files-us-bank-charter-2026",
  "stablecoins-cross-border-payments-2026",
  "us-remittance-excise-tax-takes-effect-2026",
]); // 7 URLs

export const SITEMAP_RATE_PAIR_SLUGS = new Set<string>([
  "eur-to-gbp",
  "eur-to-usd",
  "gbp-to-eur",
  "gbp-to-inr",
  "gbp-to-pkr",
  "gbp-to-usd",
  "usd-to-aud",
  "usd-to-brl",
  "usd-to-cad",
  "usd-to-gbp",
  "usd-to-jpy",
  "usd-to-php",
]); // 12 URLs

export const SITEMAP_RATE_HISTORY_SLUGS = new Set<string>([
  "aud-to-eur",
  "aud-to-php",
  "aud-to-usd",
  "cad-to-eur",
  "cad-to-gbp",
  "chf-to-eur",
  "eur-to-cop",
  "eur-to-gbp",
  "eur-to-inr",
  "eur-to-try",
  "gbp-to-eur",
  "gbp-to-inr",
  "gbp-to-usd",
  "gbp-to-zar",
  "sgd-to-php",
  "usd-to-brl",
  "usd-to-cad",
  "usd-to-cop",
  "usd-to-eur",
  "usd-to-inr",
  "usd-to-mxn",
  "usd-to-php",
]); // 22 URLs

export const SITEMAP_SWIFT_SLUGS = new Set<string>([
  "georgia",
]); // 1 URLs

export const SITEMAP_BUSINESS_SLUGS = new Set<string>([
  "b2b-transfers",
  "vendor-payments",
]); // 2 URLs
